/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#4682c2';
const tintColorDark = '#fff';

export const COLORS = {
  light: {
    // main colors
    grey: '#DEDDE0',
    greyCe: '#CECECE',
    greyE5: '#E5E5E5',
    greyF5: '#F5F5F5',
    greyF0: '#F0F0F0',
    greyCC: '#CCCCCC',
    greyB0: '#B0B0B0',
    greyA0: '#A0A0A0',
    grey90: '#909090',
    grey50: '#505050',
    grey70: '#707070',
    white: '#FFFFFF',
    black: '#000000',

    // app colors
    text: '#11181C',
    tint: tintColorLight,
    icon: '#687076',
    border: '#C5CCD6',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,

    // system message colors
    success: '#159F91',
    danger: '#FF193B',
    dangerF5: '#F54135',
    dangerBC: '#BC1823',
    dangerFF: '#FFCDD4',
    // new colors
    surface: '#fff8f6',
    surfaceDim: '#efd5cc',
    surfaceBright: '#fff8f6',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#fff1ec',
    surfaceContainer: '#ffe9e2',
    surfaceContainerHigh: '#fde3d9',
    surfaceContainerHighest: '#f8ddd4',
    onSurface: '#261813',
    onSurfaceVariant: '#5a4138',
    inverseSurface: '#3d2d27',
    inverseOnSurface: '#ffede7',
    outline: '#8e7166',
    outlineVariant: '#e2bfb3',
    surfaceTint: '#a73a00',
    primary: '#a33900',
    onPrimary: '#ffffff',
    primaryContainer: '#cc4900',
    onPrimaryContainer: '#fffbff',
    inversePrimary: '#ffb599',
    secondary: '#505f76',
    onSecondary: '#ffffff',
    secondaryContainer: '#d0e1fb',
    onSecondaryContainer: '#54647a',
    tertiary: '#005f9f',
    onTertiary: '#ffffff',
    tertiaryContainer: '#0078c7',
    onTertiaryContainer: '#fdfcff',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#ffdbce',
    primaryFixedDim: '#ffb599',
    onPrimaryFixed: '#370e00',
    onPrimaryFixedVariant: '#7f2b00',
    secondaryFixed: '#d3e4fe',
    secondaryFixedDim: '#b7c8e1',
    onSecondaryFixed: '#0b1c30',
    onSecondaryFixedVariant: '#38485d',
    tertiaryFixed: '#d1e4ff',
    tertiaryFixedDim: '#9ecaff',
    onTertiaryFixed: '#001d36',
    onTertiaryFixedVariant: '#00497c',
    background: '#ffffff',
    onBackground: '#261813',
    surfaceVariant: '#f8ddd4',

    brand: {
      highEnergyPrimary: '#EC5B13',
      offWhiteBg: '#FAFAFA',
      cardBg: '#FFFFFF',
      textSecondary: '#64748B',
      borderSoft: '#E2E8F0',
      statusCompletedText: '#1f4d29', // Sage green contrast
      statusCompletedBg: '#e9f5ec', // Muted sage green
      statusOverdueText: '#EC5B13',
      statusOverdueBg: '#FDEEE7',
      statusUpcomingText: '#64748B',
      statusUpcomingBg: '#f1f5f9', // Muted soft blue
    },
  },
  dark: {
    // main colors
    grey: '#DEDDE0',
    greyCe: '#CECECE',
    greyE5: '#E5E5E5',
    grey70: '#707070',
    greyF5: '#F5F5F5',
    greyF0: '#F0F0F0',
    greyCC: '#CCCCCC',
    greyB0: '#B0B0B0',
    greyA0: '#A0A0A0',
    grey90: '#909090',
    grey50: '#505050',
    white: '#FFFFFF',
    black: '#000000',

    // app colors
    text: '#ECEDEE',
    tint: tintColorDark,
    icon: '#9BA1A6',
    border: '#3E4042',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
    // new colors
    surface: '#fff8f6',
    surfaceDim: '#efd5cc',
    surfaceBright: '#fff8f6',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#fff1ec',
    surfaceContainer: '#ffe9e2',
    surfaceContainerHigh: '#fde3d9',
    surfaceContainerHighest: '#f8ddd4',
    onSurface: '#261813',
    onSurfaceVariant: '#5a4138',
    inverseSurface: '#3d2d27',
    inverseOnSurface: '#ffede7',
    outline: '#8e7166',
    outlineVariant: '#e2bfb3',
    surfaceTint: '#a73a00',
    primary: '#a33900',
    onPrimary: '#ffffff',
    primaryContainer: '#cc4900',
    onPrimaryContainer: '#fffbff',
    inversePrimary: '#ffb599',
    secondary: '#505f76',
    onSecondary: '#ffffff',
    secondaryContainer: '#d0e1fb',
    onSecondaryContainer: '#54647a',
    tertiary: '#005f9f',
    onTertiary: '#ffffff',
    tertiaryContainer: '#0078c7',
    onTertiaryContainer: '#fdfcff',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#ffdbce',
    primaryFixedDim: '#ffb599',
    onPrimaryFixed: '#370e00',
    onPrimaryFixedVariant: '#7f2b00',
    secondaryFixed: '#d3e4fe',
    secondaryFixedDim: '#b7c8e1',
    onSecondaryFixed: '#0b1c30',
    onSecondaryFixedVariant: '#38485d',
    tertiaryFixed: '#d1e4ff',
    tertiaryFixedDim: '#9ecaff',
    onTertiaryFixed: '#001d36',
    onTertiaryFixedVariant: '#00497c',
    background: '#ffffff',
    onBackground: '#261813',
    surfaceVariant: '#f8ddd4',

    // system message colors
    success: '#159F91',
    danger: '#FF193B',
    dangerF5: '#F54135',
    dangerBC: '#BC1823',
    dangerFF: '#FFCDD4',
    // brand
    brand: {
      highEnergyPrimary: '#EC5B13',
      offWhiteBg: '#FAFAFA',
      cardBg: '#FFFFFF',
      textSecondary: '#64748B',
      borderSoft: '#E2E8F0',
      statusCompletedText: '#1f4d29', // Sage green contrast
      statusCompletedBg: '#e9f5ec', // Muted sage green
      statusOverdueText: '#EC5B13',
      statusOverdueBg: '#FDEEE7',
      statusUpcomingText: '#64748B',
      statusUpcomingBg: '#f1f5f9', // Muted soft blue
    },
  },
};
