-- AutoPilot — the rest of the services
--
-- NOT APPLIED. Run this in the Supabase SQL editor. It is the parts of
-- 001_app_gap.sql that the Services tab needs, lifted out so they can go
-- without the rest (profiles, vehicle columns, cascades).
--
-- What each section unlocks:
--   1. Reminders   distance triggers, repeat intervals, a service type and notes
--   2. Documents   type, issue/expiry dates and notes — expiry tracking
--   3. Storage     attaching a scan or PDF to a document
--   4. Climate     history that survives an app restart
--   5. Trips       plans that survive an app restart
--
-- Until this has run, the app hides the fields sections 1–3 add (see
-- UNBACKED_FIELDS in apis/config.ts), and climate and trips live in memory
-- for the session only. After it has run, remove the matching entries from
-- UNBACKED_FIELDS, flip `climate` and `trips` in BACKENDS, and widen the
-- reminder and document mappers in apis/repositories to read the new columns.
--
-- Re-runnable: every statement is `if not exists` or `or replace`.

begin;

-- ── 1. Reminders ─────────────────────────────────────────────────────────────

alter table public.service_reminders
  add column if not exists title               text,
  add column if not exists service_type        bigint references public.services_types (id),
  add column if not exists trigger             text not null default 'date',
  add column if not exists due_odometer        int,
  add column if not exists repeat_every_months int,
  add column if not exists repeat_every_km     int;

-- A distance-only reminder has no date to store.
alter table public.service_reminders alter column date drop not null;

-- The app has been writing titles into `notes`; copy them across. `notes` is
-- left as it is, because the app still reads titles from it until the
-- reminder mapper is switched over to `title`.
update public.service_reminders
   set title = notes
 where title is null
   and notes is not null;

-- ── 2. Documents ─────────────────────────────────────────────────────────────

alter table public.vehicle_documents
  add column if not exists type        text not null default 'other',
  add column if not exists issue_date  date,
  add column if not exists expiry_date date,
  add column if not exists file_name   text,
  add column if not exists file_size   bigint,
  add column if not exists mime_type   text,
  add column if not exists notes       text;

-- A document can be recorded before its scan is attached.
alter table public.vehicle_documents alter column image drop not null;

-- ── 3. Storage ───────────────────────────────────────────────────────────────
-- The `storage` bucket has no policies at all, so every upload is refused.
-- The app writes to `<user id>/<timestamp>-<filename>`.

drop policy if exists "vehicle_documents_owner" on storage.objects;
create policy "vehicle_documents_owner" on storage.objects
  for all to authenticated
  using (
    bucket_id = 'storage'
    and auth.uid()::text = (storage.foldername(name))[1]
  )
  with check (
    bucket_id = 'storage'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

-- ── 4. Climate & comfort ─────────────────────────────────────────────────────

create table if not exists public.climate_records (
  id              bigint generated by default as identity primary key,
  vehicle_id      bigint  not null references public.vehicles on delete cascade,
  type            text    not null,
  date            date    not null,
  odometer        int,
  cost            numeric,
  currency        text default 'EGP',
  notes           text,
  interval_months int     not null default 12,
  created_at      timestamptz not null default now()
);

create index if not exists climate_vehicle_idx
  on public.climate_records (vehicle_id, date desc);

alter table public.climate_records enable row level security;
grant select, insert, update, delete on public.climate_records to authenticated;

drop policy if exists "climate to vehicle" on public.climate_records;
create policy "climate to vehicle" on public.climate_records
  for all to authenticated
  using (vehicle_id in (select id from public.vehicles where user_id = auth.uid()))
  with check (vehicle_id in (select id from public.vehicles where user_id = auth.uid()));

-- ── 5. Roadtrip planner ──────────────────────────────────────────────────────

create table if not exists public.trips (
  id                   bigint generated by default as identity primary key,
  vehicle_id           bigint  not null references public.vehicles on delete cascade,
  name                 text    not null,
  origin               text    not null,
  destination          text    not null,
  distance_km          numeric not null,
  is_round_trip        boolean not null default true,
  departure_date       date    not null,
  return_date          date,
  fuel_price_per_liter numeric not null default 0,
  currency             text default 'EGP',
  travellers           int     not null default 1,
  notes                text,
  checklist            jsonb   not null default '[]'::jsonb,
  created_at           timestamptz not null default now()
);

create index if not exists trips_vehicle_idx on public.trips (vehicle_id, departure_date);

alter table public.trips enable row level security;
grant select, insert, update, delete on public.trips to authenticated;

drop policy if exists "trips to vehicle" on public.trips;
create policy "trips to vehicle" on public.trips
  for all to authenticated
  using (vehicle_id in (select id from public.vehicles where user_id = auth.uid()))
  with check (vehicle_id in (select id from public.vehicles where user_id = auth.uid()));

commit;
